"""empty message

Revision ID: 44f9466d49e7
Revises: 
Create Date: 2022-02-20 23:37:05.395899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f9466d49e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vocab_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('words', sa.String(length=360), nullable=True),
    sa.Column('words2', sa.String(length=360), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_set_name'), 'vocab_set', ['name'], unique=True)
    op.create_index(op.f('ix_vocab_set_words'), 'vocab_set', ['words'], unique=False)
    op.create_index(op.f('ix_vocab_set_words2'), 'vocab_set', ['words2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_set_words2'), table_name='vocab_set')
    op.drop_index(op.f('ix_vocab_set_words'), table_name='vocab_set')
    op.drop_index(op.f('ix_vocab_set_name'), table_name='vocab_set')
    op.drop_table('vocab_set')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
